apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrowers
  namespace: custom-mesh
spec:
  selector:
    matchLabels:
      app: borrowers
  template:
    metadata:
      labels:
        app: borrowers
      annotations:
        inject-sidecar: "true"
    spec:
      containers:
      - name: borrowers
        image: payaljain/sample-service-borrowers:1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: borrowers-service-admin
  namespace: custom-mesh
spec:
  type: LoadBalancer
  selector:
    app: borrowers
  ports:
  - port: 9901
    targetPort: 9901
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
  namespace: custom-mesh
spec:
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
      annotations:
        inject-sidecar: "true"
    spec:
      containers:
      - name: books
        image: payaljain/sample-service-books:1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: books-service
  namespace: custom-mesh
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: books
  ports:
  - port: 8081
    targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: books-service-admin
  namespace: custom-mesh
spec:
  type: LoadBalancer
  selector:
    app: books
  ports:
  - port: 9901
    targetPort: 9901
---