apiVersion: v1
kind: Namespace
metadata:
  name:  envoy-research
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-service
  namespace: envoy-research
spec:
  selector:
    matchLabels:
      app: dummy-service
  template:
    metadata:
      labels:
        app: dummy-service
    spec:
      volumes:
      - name: config
        configMap:
          name: envoy-config
      containers:
      - name: app1
        image: payaljain/xds-dummy-service:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
      - name: envoy
        image: envoyproxy/envoy
        args:
        - -c
        - /etc/envoy/envoy.yaml
        - --service-cluster
        - ${MY_CLUSTER_NAME}
        - --service-node
        - ${MY_NAME}
        - -l
        - trace
        env:
        - name: MY_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_CLUSTER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: config
          mountPath: /etc/envoy
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 9901
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-admin-service
  namespace: envoy-research
spec:
  type: LoadBalancer
  selector:
    app: dummy-service
  ports:
  - port: 9901
    targetPort: 9901
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: envoy-research
data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
    dynamic_resources:
      lds_config:
        api_config_source:
          api_type: REST
          refresh_delay: 10s
          cluster_names:
          - xds_cluster
      cds_config:
        api_config_source:
          api_type: REST
          refresh_delay: 10s
          cluster_names:
          - xds_cluster
          # grpc_services:
          #   envoy_grpc:
          #     cluster_name: xds_cluster
    static_resources:
      # listeners:
      # - name: listener_0
      #   address:
      #     socket_address:
      #       address: 127.0.0.1
      #       port_value: 80
      #   filter_chains:
      #   - filters:
      #     - name: envoy.http_connection_manager
      #       config:
      #         stat_prefix: ingress_http
      #         codec_type: AUTO
      #         route_config:
      #           name: local_route
      #           virtual_hosts:
      #           - name: local_service
      #             domains: ["*"]
      #             routes:
      #             - match:
      #                 prefix: "/"
      #               route:
      #                 host_rewrite: www.google.com
      #                 cluster: service_google
      #         http_filters:
      #         - name: envoy.router
      clusters:
      - name: xds_cluster
        connect_timeout:  0.25s
        type: LOGICAL_DNS
        # Comment out the following line to test on v6 networks
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        hosts:
        - socket_address:
            address: xds-service
            port_value: 80
---










