apiVersion: apps/v1
kind: Deployment
metadata:
  name: injector-mutating-hook
  namespace: custom-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: injector-mutating-hook
  template:
    metadata:
      labels:
        app: injector-mutating-hook
    spec:
      volumes:
        - name: certs
          secret:
            secretName: injector-certs
      containers:
      - name: injector-mutating-hook
        imagePullPolicy: Always
        image: payaljain/node-injector-mutating-hook:1
        volumeMounts:
          - name: certs
            mountPath: /app/certs
---
apiVersion: v1
kind: Service
metadata:
  name: injector-svc
  namespace: custom-mesh
spec:
  type: ClusterIP
  selector:
    app: injector-mutating-hook
  ports:
  - port: 443
    targetPort: 443
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: custom-mesh
data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
    dynamic_resources:
      lds_config:
        api_config_source:
          api_type: REST
          refresh_delay: 10s
          cluster_names:
          - xds_cluster
      cds_config:
        api_config_source:
          api_type: REST
          refresh_delay: 10s
          cluster_names:
          - xds_cluster
    static_resources:
      clusters:
      - name: xds_cluster
        connect_timeout:  0.25s
        type: LOGICAL_DNS
        # Comment out the following line to test on v6 networks
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        hosts:
        - socket_address:
            address: xds-service
            port_value: 80
      - name: local_cluster
        connect_timeout:  0.25s
        type: STATIC
        # Comment out the following line to test on v6 networks
        # lb_policy: ROUND_ROBIN
        hosts:
        - socket_address:
            address: 127.0.0.1
            port_value: 8081



