apiVersion: apps/v1
kind: Deployment
metadata:
  name: injector-mutating-hook
  namespace: custom-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: injector-mutating-hook
  template:
    metadata:
      labels:
        app: injector-mutating-hook
    spec:
      volumes:
        - name: certs
          secret:
            secretName: injector-certs
      containers:
      - name: injector-mutating-hook
        imagePullPolicy: Always
        image: payaljain/node-injector-mutating-hook:1
        volumeMounts:
          - name: certs
            mountPath: /app/certs
---
apiVersion: v1
kind: Service
metadata:
  name: injector-svc
  namespace: custom-mesh
spec:
  type: ClusterIP
  selector:
    app: injector-mutating-hook
  ports:
  - port: 443
    targetPort: 443


