apiVersion: v1
kind: Pod
metadata:
  annotations:
    inject-sidecar: "true"
  labels:
    run: ng
  name: ng
  namespace: custom-mesh
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: ng
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-admin
spec:
  selector:
    run: ng
  ports:
  - port: 9901
    targetPort: 9901
  type: LoadBalancer


